version: "3.9"
services:
  node:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    volumes:
      - ./node_modules:/node_modules
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      TZ: Asia/Tokyo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data
  mongo-express:
    image: mongo-express
    restart: always
    links:
      - "mongodb:mongo"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
