version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      TZ: Asia/Tokyo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data
